server:
  port: 8050

spring:
  application:
    name: demo-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

logging:
  level:
    root: INFO

zuul:
  ignoredServices: '*'
  routes:
    app-provider-user:            #名称随意，唯一就好
      path: /user/**
      serviceId: consumer-hystrix
    app-sidecar:                  #通过sidecar调用nodejs的服务
      path: /sidecar/**
      serviceId: sidecar
